server:
  port: 0
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:postgres://pmeijlwspwsoqr:89d2b57e172bc81927adc6c4e5b5979e78ade362569ef8bed9768d06c3ffe78c@ec2-54-235-244-185.compute-1.amazonaws.com:5432/d2hsai66bml5v7
    username: pmeijlwspwsoqr
    password: 89d2b57e172bc81927adc6c4e5b5979e78ade362569ef8bed9768d06c3ffe78c
    driver-class-name: org.postgresql.Driver
eureka:
  instance:
    hostname: servico-usuarios-1-unialfa.herokuapp.com
    secure-port-enabled: true
    non-secure-port-enabled: false
  client:
    service-url:
      defaultZone: https://eureka-unialfa.herokuapp.com/eureka/
    healthcheck: true